Repository dnd-side-project/dnd-9th-6-frontend, pull requests merged in 2023-08, with the labels that each got.

#2 Init next js & eslint
  .eslintrc.json
  .gitignore
  next-env.d.ts
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  tsconfig.json
  yarn-error.log
  yarn.lock
Labels: ✅완료

#5 Add styled-components theme
  src/app/layout.tsx
  src/styles/theme.ts
Labels: 💄 STYLE

#6 Enhance ThemeProvider setting
  src/app/fonts/PretendardVariable.woff2
  src/app/layout.tsx
  src/components/providers/StyledThemeProvider.tsx
Labels: 💄 STYLE

#7 Fix eslint&tsconfig setting
  .eslintrc.json
  src/app/page.tsx
  tsconfig.json
Labels: 📄 DOCS

#11 Refactoring Button Component
  src/@types/button.d.ts
  src/components/Button/index.tsx
  src/components/Buttons/Button.tsx
  src/components/buttons/Button.tsx
  src/components/buttons/button.tsx
Labels: ♻️ REFACTOR

#9 Add button component
  package.json
  src/app/layout.tsx
  src/components/Button/index.tsx
  src/components/providers/ChakraUIProvider.tsx
  src/components/providers/StyledThemeProvider.tsx
  src/styles/theme/components/buttonTheme.ts
  src/styles/theme/foundations/colors.ts
  src/styles/theme/foundations/index.ts
  src/styles/theme/foundations/shadow.ts
  src/styles/theme/foundations/typo.ts
  src/styles/theme/index.ts
  src/styles/theme/styles.ts
  yarn.lock
Labels: 💄 STYLE

#12 Add Tabs Components
  package.json
  src/app/layout.tsx
  src/components/Tabs/index.tsx
  src/components/providers/ChakraUIProvider.tsx
  src/styles/theme/components/tabsTheme.ts
  src/styles/theme/foundations/typo.ts
  src/styles/theme/index.ts
  yarn.lock
Labels: 💄 STYLE

#15 Add axios instance & interceptors
  package.json
  src/apis/auth/index.ts
  src/apis/index.ts
  src/app/(loginRoutes)/login/google/page.tsx
  src/app/(loginRoutes)/login/kakao/page.tsx
  src/app/(loginRoutes)/login/page.tsx
  src/app/login/page.tsx
  src/constants/api.ts
  src/hooks/useSocialLogin.ts
  src/recoil/types/user.ts
  src/utils/returnFetch.ts
  src/utils/returnFetchJson.ts
  src/utils/returnFetchThrowingErrorByStatusCode.ts
  yarn.lock
Labels: ✨ FEATURE

#8 Add axios Setting & login Logic
  package.json
  src/apis/auth/index.ts
  src/apis/index.ts
  src/app/(loginRoutes)/login/google/page.tsx
  src/app/(loginRoutes)/login/kakao/page.tsx
  src/app/(loginRoutes)/login/page.tsx
  src/constants/api.ts
  src/constants/http.ts
  src/constants/routes.ts
  src/hooks/useSocialLogin.ts
  src/recoil/types/user.ts
  yarn.lock
Labels: ✨ FEATURE

#18 Container
  next.config.js
  src/apis/auth/index.ts
  src/apis/index.ts
  src/app/(frameRoutes)/components/Footer/index.tsx
  src/app/(frameRoutes)/components/TopBar/index.tsx
  src/app/(frameRoutes)/home/page.tsx
  src/app/(frameRoutes)/layout.tsx
  src/app/(loginRoutes)/login/google/page.tsx
  src/app/(loginRoutes)/login/kakao/page.tsx
  src/app/layout.tsx
  src/components/AppProvider/index.tsx
  src/components/Container/index.tsx
  src/components/providers/ChakraUIProvider.tsx
  src/hooks/useSocialLogin.ts
  tsconfig.json
  yarn.lock
Labels: 💄 STYLE

#21 Enhance TooltipIcon Component
  src/components/TooltipIcon/index.tsx
Labels: 💄 STYLE

#20 Implement Checkbox Component
  src/components/Checkbox/index.tsx
  src/styles/theme/components/checkboxTheme.ts
  src/styles/theme/foundations/shadow.ts
  src/styles/theme/index.ts
Labels: 💄 STYLE

#19 Implement TooltipIcon Component
  src/assets/icons/platform/class101.svg
  src/assets/icons/platform/coloso.svg
  src/assets/icons/platform/fastcampus.svg
  src/assets/icons/platform/inflearn.svg
  src/components/TooltipIcon/index.tsx
Labels: 💄 STYLE

#22 Implement Menu Component
  next.config.js
  src/assets/icons/angle-down.svg
  src/assets/icons/angle-up.svg
  src/components/Button/index.tsx
  src/components/Menu/index.tsx
  src/styles/theme/components/menuTheme.ts
  src/styles/theme/index.ts
Labels: 💄 STYLE

#24 Component card
  src/app/layout.tsx
  src/assets/icons/bookmark-border.svg
  src/assets/icons/card/edge.svg
  src/assets/icons/card/whitebg-large.svg
  src/assets/icons/card/whitebg.svg
  src/assets/icons/glass/chat/purple.svg
  src/assets/icons/glass/fire/purple.svg
  src/assets/icons/glass/meteor/purple.svg
  src/assets/icons/platform/class101-16.svg
  src/assets/icons/platform/class101-24.svg
  src/assets/icons/platform/class101-32.svg
  src/assets/icons/platform/class101-40.svg
  src/assets/icons/platform/coloso-16.svg
  src/assets/icons/platform/coloso-24.svg
  src/assets/icons/platform/coloso-32.svg
  src/assets/icons/platform/coloso-40.svg
  src/assets/icons/platform/fastcampus-16.svg
  src/assets/icons/platform/fastcampus-24.svg
  src/assets/icons/platform/fastcampus-32.svg
  src/assets/icons/platform/fastcampus-40.svg
  src/assets/icons/platform/inflearn-16.svg
  src/assets/icons/platform/inflearn-24.svg
  src/assets/icons/platform/inflearn-32.svg
  src/assets/icons/platform/inflearn-40.svg
  src/assets/icons/rating/star.svg
  src/components/Badge/index.tsx
  src/components/Card/CoverCard.tsx
  src/components/Card/HorizontalCard.tsx
  src/components/Card/LandScapeCard.tsx
  src/components/Card/OutlinedCard.tsx
  src/components/Card/SquareCard.tsx
  src/components/Card/index.tsx
  src/styles/theme/components/buttonTheme.ts
  src/styles/theme/foundations/typo.ts
Labels: 💄 STYLE

#25 Implement Scope Page
  package.json
  public/images/HorizontalCard.png
  public/images/Squarecard.png
  public/images/demo.png
  public/images/demo2.png
  src/app/(frameRoutes)/layout.tsx
  src/app/(frameRoutes)/scope/page.tsx
  yarn.lock
Labels: 💄 STYLE, ✨ FEATURE

#26 Add Component
  src/app/layout.tsx
  src/assets/icons/bookmark-border.svg
  src/assets/icons/card/edge.svg
  src/assets/icons/card/whitebg-large.svg
  src/assets/icons/card/whitebg.svg
  src/assets/icons/glass/chat/purple.svg
  src/assets/icons/glass/fire/purple.svg
  src/assets/icons/glass/meteor/purple.svg
  src/assets/icons/platform/class101-16.svg
  src/assets/icons/platform/class101-24.svg
  src/assets/icons/platform/class101-32.svg
  src/assets/icons/platform/class101-40.svg
  src/assets/icons/platform/coloso-16.svg
  src/assets/icons/platform/coloso-24.svg
  src/assets/icons/platform/coloso-32.svg
  src/assets/icons/platform/coloso-40.svg
  src/assets/icons/platform/fastcampus-16.svg
  src/assets/icons/platform/fastcampus-24.svg
  src/assets/icons/platform/fastcampus-32.svg
  src/assets/icons/platform/fastcampus-40.svg
  src/assets/icons/platform/inflearn-16.svg
  src/assets/icons/platform/inflearn-24.svg
  src/assets/icons/platform/inflearn-32.svg
  src/assets/icons/platform/inflearn-40.svg
  src/assets/icons/rating/star.svg
  src/components/Badge/index.tsx
  src/components/Card/CoverCard.tsx
  src/components/Card/HorizontalCard.tsx
  src/components/Card/LandScapeCard.tsx
  src/components/Card/OutlinedCard.tsx
  src/components/Card/SquareCard.tsx
  src/components/Card/index.tsx
  src/styles/theme/components/buttonTheme.ts
  src/styles/theme/foundations/typo.ts
Labels: 💄 STYLE

#27 Add Card Component Annotation
  src/components/Card/CoverCard.tsx
  src/components/Card/HorizontalCard.tsx
  src/components/Card/LandScapeCard.tsx
  src/components/Card/OutlinedCard.tsx
  src/components/Card/SquareCard.tsx
Labels: 📄 DOCS

#29 Conflict resolve
  src/app/(frameRoutes)/components/Footer/index.tsx
  src/app/(frameRoutes)/components/TopBar/index.tsx
  src/app/(frameRoutes)/home/page.tsx
  src/app/(frameRoutes)/layout.tsx
  src/assets/icons/logo-black.svg
  src/assets/icons/logo-text-white.svg
  src/components/Container/index.tsx
Labels: 💄 STYLE

#30 Fix typescript version error
  package.json
  tsconfig.json
  yarn.lock
Labels: 🐞BUG, 🏗️ INFRA

#31 Enhance TobBars Components
  src/app/(frameRoutes)/components/TopBar/index.tsx
  src/app/(frameRoutes)/scope/page.tsx
  src/components/Tabs/index.tsx
  src/styles/theme/components/tabsTheme.ts
Labels: 💄 STYLE

#33 Add Scope Page api data
  src/app/(frameRoutes)/scope/page.tsx
  src/components/Card/HorizontalCard.tsx
  src/components/Card/OutlinedCard.tsx
  src/components/Card/SquareCard.tsx
Labels: ✨ FEATURE

#34 Fix queryString query
  src/apis/scope/index.ts
Labels: 🚑 HOTFIX

#35 Add Lectures API & TYPE
  src/apis/lectures/index.ts
  src/apis/lectures/types/index.ts
  src/constants/querykeys.ts
  src/hooks/reactQuery/lectures/query.ts
Labels: ✨ FEATURE

#36 Implement lectures page (draft)
  public/images/banner.png
  public/images/bgblue.jpg
  src/app/(frameRoutes)/lectures/page.tsx
Labels: 💄 STYLE
